# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/mankaic/nexys-a7-100t-master.xdc

# IP: ip/road7/road7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==road7 || ORIG_REF_NAME==road7} -quiet] -quiet
