# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mankaic/Desktop/project_1/project_1.runs/synth_1/game_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 16
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mankaic/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/mankaic/Desktop/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo /home/mankaic/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/mankaic/car_green_5_30x51_12bit.coe
add_files /home/mankaic/land_grass04_32x32_12bit.coe
add_files /home/mankaic/road_asphalt04_32x32_12bit.coe
add_files /home/mankaic/road_asphalt08_32x32_12bit.coe
add_files /home/mankaic/road_asphalt09_32x32_12bit.coe
add_files /home/mankaic/road_asphalt21_32x32_12bit.coe
add_files /home/mankaic/road_asphalt22_32x32_12bit.coe
add_files /home/mankaic/road_asphalt26_32x32_12bit.coe
add_files /home/mankaic/road_asphalt27_32x32_12bit.coe
add_files /home/mankaic/road_asphalt28_32x32_12bit.coe
add_files /home/mankaic/road_asphalt45_32x32_12bit.coe
add_files /home/mankaic/road_asphalt46_32x32_12bit.coe
read_verilog -library xil_defaultlib -sv {
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/background.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/moving_car.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/vga_out.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/game_top.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/imports/mankaic/image_rom_reader.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/imports/mankaic/drawcon.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/collision_mask.sv
  /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/new/tile_mask.sv
}
read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road7/road7.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road7/road7_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/green_car/green_car.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/green_car/green_car_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/grass/grass.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/grass/grass_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road1/road1.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road1/road1_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road2/road2.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road2/road2_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road3/road3.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road3/road3_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road4/road4.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road4/road4_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road5/road5.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road5/road5_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road6/road6.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road6/road6_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road8/road8.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road8/road8_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road9/road9.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road9/road9_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road10/road10.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road10/road10_ooc.xdc]

read_ip -quiet /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mankaic/Desktop/project_1/project_1.srcs/constrs_1/imports/mankaic/nexys-a7-100t-master.xdc
set_property used_in_implementation false [get_files /home/mankaic/Desktop/project_1/project_1.srcs/constrs_1/imports/mankaic/nexys-a7-100t-master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top game_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef game_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file game_top_utilization_synth.rpt -pb game_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
