# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road5/road5.xci
# IP: The module: 'road5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road5/road5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'road5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mankaic/Desktop/project_1/project_1.srcs/sources_1/ip/road5/road5.xci
# IP: The module: 'road5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mankaic/Desktop/project_1/project_1.gen/sources_1/ip/road5/road5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'road5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
