webtalk_init -webtalk_dir /home/mankaic/Desktop/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/test_signals_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct  5 16:37:35 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f00a33c5-d967-4a36-bb1d-cc85f55763fe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "051d06ddf2d64e5f91f1ef90c01ee499" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10020 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "42.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "120900_KB" -context "xsim\\usage"
webtalk_transmit -clientid 227429650 -regid "211887999_1777552194_210720986_228" -xml /home/mankaic/Desktop/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/test_signals_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/mankaic/Desktop/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/test_signals_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/mankaic/Desktop/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/test_signals_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
